sudo: false
language: erlang
addons:
  apt:
    packages:
      - xsltproc
services:
  - rabbitmq
otp_release:
  - "R16B03-1"
  - "17.5"
  - "18.0"
install:
  - if [ ! -d "$HOME/rabbitmq-public-umbrella/.git" ]; then git clone https://github.com/rabbitmq/rabbitmq-public-umbrella.git $HOME/rabbitmq-public-umbrella; fi
  - cd $HOME/rabbitmq-public-umbrella
  - make co
  - make up
before_script:
  - cd $HOME/rabbitmq-public-umbrella/rabbitmq-test
script: make lite
before_cache:
  - rm -rf ${TEST_DIR}
  - cd $HOME
cache:
  apt: true
  directories:
    - $HOME/rabbitmq-public-umbrella
